/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;


public class finalsframe extends javax.swing.JFrame {

    /**
     * Creates new form finalsframe
     */
    public finalsframe() {
        try {
            initComponents();
            dbConnection();
            loadTable();
        } catch (SQLException ex) {
            Logger.getLogger(finalsframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    static String tableID;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mnametxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        femalerdo = new javax.swing.JRadioButton();
        malerdo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        contacttxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        blockcmbx = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        residentSpr = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lotcmbx = new javax.swing.JComboBox<>();
        insertBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consensus");

        jLabel2.setText("First name: ");

        jLabel3.setText("Middle name: ");

        jLabel4.setText("Last name:");

        gender.add(femalerdo);
        femalerdo.setText("Female");

        gender.add(malerdo);
        malerdo.setText("Male");
        malerdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malerdoActionPerformed(evt);
            }
        });

        jLabel5.setText("Gender:");

        jLabel6.setText("Contact:");

        jLabel7.setText("Block: ");

        blockcmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));

        jLabel8.setText("Lot: ");

        residentSpr.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setText("No. of residents");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "firstName", "middleName", "lastName", "contact", "gender", "block", "lot", "no_residents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lotcmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        insertBtn.setText("INSERT");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(femalerdo)
                                        .addGap(18, 18, 18)
                                        .addComponent(malerdo))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(fnametxt)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contacttxt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(residentSpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blockcmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lotcmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 75, Short.MAX_VALUE)))
                        .addGap(57, 57, 57)
                        .addComponent(insertBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(blockcmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lotcmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(femalerdo)
                    .addComponent(malerdo)
                    .addComponent(jLabel5)
                    .addComponent(residentSpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void malerdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malerdoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_malerdoActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to add this to your database?","Confirmation", JOptionPane.YES_NO_OPTION);
        if(opt == 0){
            try {
                String fname = fnametxt.getText();
                String mname = mnametxt.getText();
                String lname = lnametxt.getText();
                String gender = " ";
                String contactNo = contacttxt.getText();
                String blk = String.valueOf(blockcmbx.getSelectedItem());
                String lot = lotcmbx.getSelectedItem().toString();
                String residents = residentSpr.getValue().toString();
                
                //gender rdoBtns
                if(malerdo.isSelected()){
                    gender = "Male";
                }
                if(femalerdo.isSelected()){
                    gender = "Female";
                }
                pst = con.prepareCall("INSERT INTO residents(ID , firstName, middleName, lastName, contact, gender, block, lot, no_residents )VALUES(?,?,?,?,?,?,?,?,?)");
                pst.setString(1, "0");
                pst.setString(2, fname);
                pst.setString(3, mname);
                pst.setString(4, lname);
                pst.setString(5, contactNo);
                pst.setString(6, gender);
                pst.setString(7, blk);
                pst.setString(8, lot);
                pst.setString(9, residents);
                
                int resp = pst.executeUpdate();
                if(resp == 1){
                    loadTable();
                    JOptionPane.showMessageDialog(this, "Added successfully.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(finalsframe.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
    }//GEN-LAST:event_insertBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
       
            try {
                String fname = fnametxt.getText();
                String mname = mnametxt.getText();
                String lname = lnametxt.getText();
                String gender = " ";
                String contactNo = contacttxt.getText();
                String blk = blockcmbx.getSelectedItem().toString();
                String lot = lotcmbx.getSelectedItem().toString();
                String residents = residentSpr.getValue().toString();
                
                //gender rdoBtns
                if(malerdo.isSelected()){
                    gender = "Male";
                }
                if(femalerdo.isSelected()){
                    gender = "Female";
                }
                pst = con.prepareCall("UPDATE residents SET firstName=?, middleName=?, lastName=?,contact=?, gender=?, block=?, lot=?, no_residents=? WHERE ID=?");
             
                pst.setString(1, fname);
                pst.setString(2, mname);
                pst.setString(3, lname);
                pst.setString(4, contactNo);
                pst.setString(5, gender);
                pst.setString(6, blk);
                pst.setString(7, lot);
                pst.setString(8, residents);
                pst.setString(9, tableID);
                
                int resp = pst.executeUpdate();
                if(resp == 1){
                    loadTable();
                    JOptionPane.showMessageDialog(this, "Added successfully.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(finalsframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            // TODO add your handling code here:
            int test = jTable1.getSelectedRow();
            tableID = jTable1.getValueAt(test, 0).toString();
            
            pst = con.prepareStatement("SELECT * FROM residents WHERE ID=?");
            pst.setString(1, tableID.toString());
                            
            rs = pst.executeQuery();
            if(rs.next()==true){
                int value = Integer.parseInt(rs.getString("no_residents"));//[1] convert muna sa int ang spinner value
                fnametxt.setText(rs.getString("firstName"));
                mnametxt.setText(rs.getString("middleName"));
                lnametxt.setText(rs.getString("lastName"));
                contacttxt.setText(rs.getString("contact"));
                if(rs.getString("gender").equals("Female")){
                    femalerdo.setSelected(true);
                }
                if(rs.getString("gender").equals("Male")){
                    malerdo.setSelected(true);
                }
                blockcmbx.setSelectedItem(rs.getString("block"));
                lotcmbx.setSelectedItem(rs.getString("lot"));
                residentSpr.setValue(value);//[2] ito kasunod after conversion
            }
        } catch (SQLException ex) {
            Logger.getLogger(finalsframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int confirmDelete = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this in the database?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(confirmDelete ==0){
              try {
                pst = con.prepareStatement("DELETE FROM residents WHERE ID=?");
                pst.setString(1, tableID);
                
                int resp = pst.executeUpdate();
                if(resp==1){
                    JOptionPane.showMessageDialog(this, "Data has been deleted successfully.");
                    loadTable();
                }
            } catch (SQLException ex) {
                Logger.getLogger(finalsframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_deleteBtnActionPerformed
    private void dbConnection() throws SQLException{
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/consensus","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(finalsframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadTable(){
        try {
            int count;
            pst = con.prepareStatement("SELECT * FROM residents");
            
            rs = pst.executeQuery();
            com.mysql.cj.jdbc.result.ResultSetMetaData rss = (com.mysql.cj.jdbc.result.ResultSetMetaData) rs.getMetaData();
            count = rss.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1; a<=count; a++){
                    v2.add(rs.getString("ID"));
                    v2.add(rs.getString("firstName"));
                    v2.add(rs.getString("middleName"));
                    v2.add(rs.getString("lastName"));
                    v2.add(rs.getString("contact"));
                    v2.add(rs.getString("gender"));
                    v2.add(rs.getString("block"));
                    v2.add(rs.getString("lot"));
                    v2.add(rs.getString("no_residents"));
                }
                df.addRow(v2);
            }
            /**
             * @param args the command line arguments
             */
        } catch (SQLException ex) {
            Logger.getLogger(finalsframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finalsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finalsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finalsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finalsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalsframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> blockcmbx;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JRadioButton femalerdo;
    private javax.swing.JTextField fnametxt;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JComboBox<String> lotcmbx;
    private javax.swing.JRadioButton malerdo;
    private javax.swing.JTextField mnametxt;
    private javax.swing.JSpinner residentSpr;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
